apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: kafka-consumer-log-pvc
  namespace: tpebnkdmipmlt
spec:
  storageClassName: tpebnkdmipmlt-sc-unvskt
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
status: {}