apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-stearming-SK0002
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-stearming-SK0002
  template:
    metadata:
      labels:
        app: model-stearming-SK0002
    spec:
      containers:
        - name: model-stearming-SK0002
          image: registry.groupt.fbt.com/tpebnkdmipmlt/kafka-consumer:0.0.3
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "172.16.240.151:9092,172.16.240.152:9092,172.16.240.153:9092"
            - name: KAFKA_GROUP_ID
              value: "model-stearming-SK0002"
            - name: KAFKA_TOPICS
              value: "CCARDTD_STREAM_FINAL"
            - name: KAFKA_AUTO_OFFSET_RESET
              #value: "latest"
              value: "earliest"
            - name: ROCKSDB_PATH
              value: "/state/checkpoints"
            - name: CHECKPOINT_EVERY_RECORDS
              value: "1000"
            - name: CHECKPOINT_EVERY_SECONDS
              value: "5"
            - name: COMMIT_KAFKA_OFFSETS
              value: "true"
            - name: POLL_TIMEOUT_SECONDS
              value: "1.0"
            - name: LOG_PATH
              value: /opt/logs
            - name: LOG_FILENAME
              value: model-stearming-SK0002
            - name: LOG_LEVEL
              value: INFO
          volumeMounts:
            - name: rocksdb-state
              mountPath: /state
            - name: model-stearming-code
              mountPath: /app
            - name: model-stearming-log
              mountPath: /opt/logs
          resources:
            requests:
              cpu: 25m
              memory: 500Mi
            limits:
              cpu: 1
              memory: 1Gi 
      volumes:
        - name: rocksdb-state
          persistentVolumeClaim:
            claimName: model-stearming-rocksdb-state-pvc
        - name: model-stearming-code
          persistentVolumeClaim:
            claimName: model-stearming-code-pvc
        - name: model-stearming-log
          persistentVolumeClaim:
            claimName: model-stearming-log-pvc
