apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: model-stearming-rocksdb-state-pvc
  namespace: tpebnkdmipmlt
spec:
  storageClassName: tpebnkdmipmlt-sc-unvskt
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
status: {}